export const FETCH_LIST_PARTNERS = "FETCH_LIST_PARTNERS"
export const CREATE_NEW_PARTNER = "CREATE_NEW_PARTNER"
export const DELETE_PARTNER = "DELETE_PARTNER"
export const UPDATE_PARTNER = "UPDATE_PARTNER"