export const FETCH_LIST_SUPPLIERS = "FETCH_LIST_SUPPLIERS"
export const CREATE_NEW_SUPPLIER = "CREATE_NEW_SUPPLIER"
export const DELETE_SUPPLIER = "DELETE_SUPPLIER"
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER"